### ISSUE TITLE
The screen is getting white while creating split 

### ISSUE THREAD

**Issue by nenni1011** [Shiddeshwaran-Selvarasu/expense_manager#2]
The screen is getting flickered and got white in the split creation screen. **NOTE** I have used the dark mode in mobile.

![image](https://github.com/Shiddeshwaran-Selvarasu/expense_manager/assets/125565848/61d46970-ebec-48a3-9294-ba0526c9df1d)

**Comment by Shiddeshwaran-Selvarasu** [comment]
@nenni1011 resolved this issue verify the same

**Comment by nenni1011** [comment]
@Shiddeshwaran-Selvarasu Thanks for the update, will verify and close the issue
