### ISSUE TITLE
Adding a new graph package

### ISSUE THREAD

**Issue by nenni1011** [Shiddeshwaran-Selvarasu/expense_manager#3]
Adding a new graph package for showing the graphs with accordance with the splits and payments we done on the specific group.

![image](https://github.com/Shiddeshwaran-Selvarasu/expense_manager/assets/125565848/d040a586-2cb9-4d76-8b76-14c512b5f38d)
![image](https://github.com/Shiddeshwaran-Selvarasu/expense_manager/assets/125565848/930a16ba-bf92-4a75-9698-1c5953f99944)

**Comment by Shiddeshwaran-Selvarasu** [comment]
Done with minimal effort
